name: ped_app
description: "Application thérapeutique pédiatrique simplifiée."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  url_launcher: ^6.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/medicaments_pediatrie.json
    - assets/annuaire.json
    - assets/protocoles/
    - assets/protocoles/etat_de_mal_epileptique.json
    - assets/protocoles/arret_cardio_respiratoire.json
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"