name: ped_app
description: "Application thérapeutique pédiatrique simplifiée."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  url_launcher: ^6.2.0
  provider: ^6.1.1
  http: ^1.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"